% generates latex code for plot generation
% u and y on the same plot
% @param data_dir : directory with delimiter-separated values (DSV) from
%                   which latex code is generated
% @param output_file : output file with latex code
function [] = generate_Latex(data_dir, output_file)

    % Output file with latex code
    fid = fopen(output_file, 'w');
    % File with opening lines of Latex file
    fid_opening = fopen('latex_opening.txt', 'r');
    
    % copy paste opening
    while feof(fid_opening) == 0
        temp = fgetl(fid_opening);
        fwrite(fid, sprintf('%s\n', fid_opening));
    end
    
    fclose(fid_opening);

    str_main = ['\\begin{figure}[tb]' newline ...
                '\\tikzsetnextfilename{%s}' newline ...
                '\\begin{tikzpicture}' newline ...
                '\\begin{groupplot}[group style={group size=1 by 2,vertical sep=\\odstepionowy},' newline ...
                '\width=\\szer,height=\\wys]' newline ...
                
                
                '\\begin{axis}[' newline ...
                'width=0.5\\textwidth,' newline ...
                'xmin=0,xmax=500,ymin=0,ymax=4,' newline ...
                'xlabel={$k$},' newline ...
                'ylabel={$y(k)$},' newline ...
                'legend pos=south east,]' newline];


    str1 = ['\\nextgroupplot' newline ...
            '[xmin=0,xmax=500,ymin=0,ymax=4,' newline ...
            'xlabel=$t \\ (\\mathrm{s})$,ylabel=$y(k)$,$y_zad(k)$,legend cell align=left,' newline ...
            'legend pos=north east]' newline ...
            strcat('\\addplot[const plot,color=black,semithick, dotted] file {', data_dir, '/', '%s};') newline ...
            strcat('\\addplot[const plot,color=blue,semithick] file {', data_dir, '/', '%s};') newline ...
            '\\legend{$y^{\mathrm{zad}}$,$y$}' newline];

    str2 = ['\\nextgroupplot' newline ...
            '[xmin=0,xmax=500,ymin=0,ymax=4,' newline ...
            'xlabel=$t \\ (\\mathrm{s})$,ylabel=$u(k)$,legend cell align=left,' newline ...
            'legend pos=north east]' newline ...
            strcat('\\addplot[const plot,color=green,semithick] file {', data_dir, '/', '%s};') newline];

    str_end = ['\\end{groupplot}' newline ...
               '\\end{tikzpicture}' newline ...
               '\\end{figure}' newline];

    for i = 3 : 3 : size(data_dir)

        fprintf(fid, str_main, data_dir(i).name(1 : size(data_dir(i).name,2) - 4) );
        fprintf(fid, str1, data_dir(i).name, data_dir(i + 1).name );
        fprintf(fid, str2, data_dir(i + 2).name );
        fprintf(fid, str_end);
    end
        fprintf(fid, ['\\end{document}' newline]);

        fclose(fid);
end

